# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='games',
            field=models.ManyToManyField(blank=True, help_text='(list of) game played on the stream.', to='streams.Game'),
        ),
    ]
