# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20180301_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='secret_art',
            field=models.ImageField(blank=True, help_text='The image drawn on the top-right secret blackboard', null=True, upload_to='', verbose_name='The secret code image'),
        ),
        migrations.AddField(
            model_name='stream',
            name='secret_meaning',
            field=models.TextField(blank=True, help_text='If discovered, the meaning behind the secret message', null=True, verbose_name='The meaning of the secret message'),
        ),
        migrations.AddField(
            model_name='stream',
            name='source',
            field=models.TextField(blank=True, help_text='Where did this information come from', verbose_name='Source of the stream schedule'),
        ),
        migrations.AddField(
            model_name='stream',
            name='source_url',
            field=models.URLField(blank=True, help_text='An URL to provide a more detailed explanation about the stream schedule', verbose_name='URL for more details on the source'),
        ),
        migrations.AddField(
            model_name='stream',
            name='square_art',
            field=models.ImageField(blank=True, help_text='The image drawn on the top-left blackboard', null=True, upload_to='', verbose_name='The image on the blackboard'),
        ),
    ]
