# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import streams.fields.activitytypefield


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_auto_20180301_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='kind',
            field=streams.fields.activitytypefield.ActivityTypeField(choices=[('0', 'Other'), ('1', 'Video game'), ('2', 'Non-video, still game'), ('3', 'Interactive story'), ('4', 'Reaction to various things'), ('5', 'Testing or tasting stuff')], default='0', help_text='The kind of activity', max_length=2, verbose_name='Kind of activity'),
        ),
        migrations.AddField(
            model_name='stream',
            name='latepatness',
            field=models.IntegerField(blank=True, help_text='How late was the stream (in minutes)', null=True, verbose_name='How late was the stream'),
        ),
    ]
