# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_auto_20180301_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='completed',
            field=models.NullBooleanField(help_text='True if the game was completed live, False if it wasn\'t. None if the game isn\'t "completable"', verbose_name='Game completed'),
        ),
        migrations.AddField(
            model_name='stream',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Stream duration (in minutes)', null=True, verbose_name='Stream duration'),
        ),
    ]
