# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 15:13
from __future__ import unicode_literals

from django.db import migrations
import streams.fields.trustlevelfield


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0006_auto_20180302_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='trust_level',
            field=streams.fields.trustlevelfield.TrustLevelField(blank=True, choices=[('0', 'The most reliable of all gave us this information, it can be trusted (probably)'), ('1', "We've got some serious hints, so it's probably alright"), ('2', "Hmm. At this point, it's 50/50 wishful thinking and unreliable source, place your bets…"), ('3', "Let's be honest, this is more like a placeholder and less like a reliable information at this point.")], help_text='How much can this information be trusted.', max_length=2, null=True, verbose_name='Level of confidence for this schedule'),
        ),
    ]
