# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0007_auto_20180305_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['-scheduled_date']},
        ),
    ]
