# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import streams.fields.youtubevideoreferencefield


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0009_auto_20180307_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', streams.fields.youtubevideoreferencefield.YoutubeVideoReferenceField(blank=True, help_text='The Youtube video ID', max_length=50, null=True, verbose_name='Video ID')),
                ('title', models.TextField(blank=True, help_text='Title of the video', null=True, verbose_name='Title of the video')),
                ('thumbnail', models.ImageField(blank=True, help_text='The thumbnail of the video', null=True, upload_to='', verbose_name='Thumbnail of the video')),
                ('duration', models.IntegerField(blank=True, help_text='Video duration (in minutes)', null=True, verbose_name='Stream duration')),
            ],
            options={
                'ordering': ['video_id'],
            },
        ),
        migrations.AddField(
            model_name='stream',
            name='archive_videos',
            field=models.ManyToManyField(blank=True, help_text='(list of) archive video from this stream', related_name='archive', to='streams.YTLink'),
        ),
        migrations.AddField(
            model_name='stream',
            name='live_video',
            field=models.ForeignKey(blank=True, help_text='Live video for this stream', null=True, on_delete=django.db.models.deletion.CASCADE, to='streams.YTLink'),
        ),
    ]
