# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 16:38
from __future__ import unicode_literals

from django.db import migrations


def get_ytlink(YTLink,
               video_id,
               video_title,
               video_duration,
               video_thumbnail):
    try:
        yt_link = YTLink.objects.get(video_id=video_id)
    except YTLink.DoesNotExist:
        yt_link = YTLink.objects.create(
            video_id=video_id,
            title=video_title,
            duration=video_duration,
            thumbnail=video_thumbnail)
    return yt_link


def create_ytlink(apps, schema_editor):
    YTLink = apps.get_model('streams', 'YTLink')
    Stream = apps.get_model('streams', 'Stream')
    for stream in Stream.objects.all():
        if stream.live_yt_ref:
            live_yt_ref = stream.live_yt_ref
            live_yt_link = get_ytlink(
                YTLink,
                live_yt_ref,
                stream.live_title,
                stream.duration,
                stream.live_thumbnail)
            stream.live_video = live_yt_link
        if stream.archive_yt_ref:
            archive_yt_ref = stream.archive_yt_ref
            archive_yt_link = get_ytlink(
                YTLink,
                archive_yt_ref,
                stream.archive_title,
                None,
                stream.archive_thumbnail)
            stream.archive_videos.add(archive_yt_link)
        stream.save()


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0010_auto_20180313_0937'),
    ]

    operations = [
        migrations.RunPython(create_ytlink),
    ]
