import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PREFIX = '/srv/www/wsgi/gtlive.info'
PROJECT_NAME = 'GTLive'
PREFIX_USER = 'www-data'
PREFIX_GROUP = 'www-data'
PREFIX_PERMISSIONS = '0755'
ORIGIN_VENV = '~/virtualenv/gtlive'
if 'GTLIVE_HOSTNAME' in os.environ:
    GTLIVE_HOSTNAME = os.environ['GTLIVE_HOSTNAME']
else:
    GTLIVE_HOSTNAME = 'gtlive.info'
if 'GTLIVE_TLS' in os.environ:
    tls_path = os.environ['GTLIVE_TLS']
else:
    tls_path = '/etc/letsencrypt/live/gtlive.info'

GTLIVE_TLS = (os.path.join(tls_path, 'privkey.pem'),
              os.path.join(tls_path, 'fullchain.pem'))

TASKS = [
    {'name': 'virtualenv',
     'desc': 'Deploy virtual python environment',
     'args': {'sourceDir': ORIGIN_VENV,
              'outputDir': 'venv',
              'pythonBin': 'python3',
              },
     },
    {'name': 'mkdir',
     'desc': 'Create log directory',
     'args': {'dirName': 'logs',
              },
     },
    {'name': 'mkdir',
     'desc': 'Create file upload directory',
     'args': {'dirName': 'uploads',
              },
     },
    {'name': 'synctree',
     'desc': 'Copying application',
     'args': {'sourceDir': 'web',
              'destDir': 'web',
              'excludePatterns': ['*.pyc'],
              },
     },
    {'name': 'synctree',
     'desc': 'Copying templates',
     'args': {'sourceDir': os.path.join('webres', 'templates'),
              'destDir': 'templates',
              },
     },
    {'name': 'manage',
     'desc': 'Collecting static files',
     'args': {'virtualEnv': ORIGIN_VENV,
              'projectLocation': os.path.join(ROOT, 'web'),
              'args': ['collectstatic',
                       '--noinput',
                       '-l',
                       ],
              'runAs': 'original',
              },
     },
    {'name': 'synctree',
     'desc': 'Copying admin files',
     'args': {'sourceDir': 'collected_statics/admin',
              'destDir': 'statics/admin',
              },
     },
    {'name': 'synctree',
     'desc': 'Copying raw files',
     'args': {'sourceDir': 'collected_statics/raw',
              'destDir': 'statics/raw',
              },
     },
    {'name': 'css',
     'desc': 'Parse CSS files',
     'args': {'sourceDir': 'collected_statics/css',
              'destinationDir': 'statics/css',
              'includeDirs': ['webres/css_include'],
              },
     },
    {'name': 'img',
     'desc': 'Process images',
     'args': {'sourceDir': 'collected_statics/img',
              'destinationDir': 'statics/img',
              },
     },
    {'name': 'js',
     'desc': 'Process Javascript',
     'args': {'sourceDir': 'collected_statics/js',
              'destinationDir': 'statics/js',
              },
     },
    {'name': 'third',
     'desc': 'Deploy third-party modules',
     'args': {'listDir': 'third',
              'jsDir': 'statics/third/js',
              'cssDir': 'statics/third/css',
              },
     },
    {'name': 'apachecfg',
     'desc': 'Apache configuration',
     'args': {'name': 'apache.conf',
              'apacheConfig': {'alias': [('u', 'uploads'),
                                         ('s', 'statics', 'cache'),
                                         ],
                               'app': 'web',
                               'venv': 'venv',
                               'loglevel': 'info',
                               'enable_compression': True,
                               'hostname': GTLIVE_HOSTNAME,
                               'tls': GTLIVE_TLS
                               },
              },
     },
    {'name': 'create_symlink',
     'desc': 'Symlink apache configuration file',
     'args': {'source': 'apache.conf',
              'destination': ('/etc/apache2/sites-available/%s.conf'
                              % PROJECT_NAME),
              },
     },
    {'name': 'a2site',
     'desc': 'Enable site',
     'args': {'enable': True,
              'siteName': PROJECT_NAME,
              },
     },
]
